version: '3'

services:
  python:
    build: .
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./data:/root/data
      - ./code:/root/code
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1